### ISSUE TITLE
Zero Output During Check Environment

### ISSUE THREAD

**Issue by monstorbak** [Dataweekends/zero_to_deep_learning_video#2]
When I run 0_Check_Environment.ipynb I do not see any outputs as specified in the Udemy tutorial or the GitHub readme. I have tried uninstalling and reinstalling the Anaconda environment successfully without luck, and I haven't seen anything on other forums that have found a solution. Any ideas on how to troubleshoot?

Thank you

**Comment by ghego** [comment]
We've updated the environment. Can you try again?
